client_name: 'hoogvliet'
price_grid_freq: 7
price_column: 'product_selling_price'
target: 'quantity_sold'
competitors: ['ah', 'lidl', 'dirck_iii', 'vomar', 'gall_gall', 'jumbo', 'dirk']
competitor_info: True
category: 'category_name_level3'
    
# Data preprocessing
filters:
    filter_product_status: True
    filter_live_products: True
    filter_sufficient_price_levels: True
    filter_low_selling_products: True
    filter_price_range: True
    min_sales: 10
    cpi: True
    
# Feature Engineering
out_of_stock_days: 7
ignore_out_of_stock_days: 2
price_lags: [1, 2, 3, 4, 5, 6, 7, 14, 21, 28] #, 90, 180, 365
price_change_columns: ['product_selling_price', 'adjusted_price'] #'adjusted_price_category', 'product_selling_price', 
min_grid_perc: -10
max_grid_perc: 10
test_end_date: '2025-10-26'
updated: False
# Modeling
test_size: 50000
n_splits: 3
optuna: False
optuna_trials: 100
leakage_warn_r2: 0.82
leakage_alert_r2: 0.87

# Elasticity
prods_per_category: 1
min_quality_tier: null # options: 'high', 'medium', null (no filtering)

# S3 data
s3_dir: 
    s3: 's3://'
    bucket: 'prime-rel-hoogvliet'
    data_prefix: 'prime/platform/temp/daily_sales/sales_with_competitors/'
    # s3: 's3://'
    # bucket: 'prime-rel-ml/'
    # data_prefix: 'data-analytics/price-elasticity/hoogvliet/data/'
    model_prefix: 'data-analytics/price-elasticity/hoogvliet/model/'
    output_prefix: 'data-analytics/price-elasticity/hoogvliet/pe_results/'
    feature_data: 'feature_data.parquet'
    feature_data_weekly: 'feature_data_weekly.parquet'
    preprocessed_data: 'preprocessed_data.parquet'
    preprocessed_data_weekly: 'preprocessed_data_weekly.parquet'
    weather: 's3://prime-rel-ml/data-analytics/price-elasticity/data/clean_weather.parquet'
    model: 'trained_model.joblib'
    price_grid: 'price_grid.pkl'
    estimations_weekly: 'estimations_weekly.parquet'
    estimations: 'estimations.parquet'
    elasticities: 'elasticities.parquet'
    elasticities_weekly: 'elasticities_weekly.parquet'
    
data_folder: 's3://prime-rel-ml/data-analytics/price-elasticity/data/'

