precalculated_features:
  - 'product_code'
  - 'adjusted_price'
  - 'promotion_indicator'
  - 'cpi'
  - 'number_of_stores'
  - 'category_name_level3'
  - 'calculated_price'
  
target: 'quantity_sold'
out_of_stock_days: 7
ignore_out_of_stock_days: 2
clients:
    spar:
        extra_columns:
        special_features:
            competitor_info: False
            lag_columns: ['adjusted_price']
            lags: True

        s3_dir: 
            s3: 's3://'
            bucket: 'prime-rel-ml/'
            prefix: 'data-analytics/price-elasticity/spar/data/'
            name: 'feature_data.parquet'
            preprocessed_data: 'preprocessed_data.parquet'
            


    hoogvliet:
        extra_columns:
            - 'ah_price'
            - 'jumbo_price'
            - 'dirk_price'
        
        
        special_features:
            competitor_info: True
            lag_columns: ['adjusted_price']
            lags: True
      
        s3_dir: 
            s3: 's3://'
            bucket: 'prime-rel-ml/'
            prefix: 'data-analytics/price-elasticity/hoogvliet/data/'
            name: 'feature_data.parquet'
            preprocessed_data: 'preprocessed_data.parquet'
            
      
    